spring:
  application:
    name: ldap

  datasource:
    url: jdbc:mysql://localhost:3306/employee_system
    username: root
    password: 16042002

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Three application properties
  ldap:
    embedded:
      port: 8090
      ldif: classpath:user-data.ldif
      base-dn: dc=springframework,dc=org
