spring:
  application:
    name: OTPAuthentication

  datasource:
    url: jdbc:mysql://localhost:3306/employee_system
    username: root
    password: 16042002

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    from-address:
    username:
    password:
    host: smtp-mail.outlook.com
    port: 587
    properties:
      mail:
        protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true